// Frontend/code/components/sample-emails.ts

export type SampleEmail = {
  student_name: string;
  uni: string;
  email: string;
  subject: string;
  body: string;
};

export const SAMPLE_EMAILS: SampleEmail[] = [
  {
    student_name: "Emre Baser 1",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Registration Deadline Question",
    body: "Hi Academic Advising Team,\n\nWhen is the deadline to register for classes?\n\nBest,\nEmre Baser 1",
  },
  {
    student_name: "Emre Baser 2",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Add Course Timing",
    body: "Hi Academic Advising Team,\n\nHow late can I add a course this term?\n\nBest,\nEmre Baser 2",
  },
  {
    student_name: "Emre Baser 3",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Registration Window",
    body: "Hi Academic Advising Team,\n\nWhen does the registration window close for fall?\n\nBest,\nEmre Baser 3",
  },
  {
    student_name: "Emre Baser 4",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Course Withdrawal Question",
    body: "Hi Academic Advising Team,\n\nHow do I drop a class after the deadline?\n\nBest,\nEmre Baser 4",
  },
  {
    student_name: "Emre Baser 5",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Need To Withdraw",
    body: "Hi Academic Advising Team,\n\nI might need to withdraw from a course because of family issues. What is the process?\n\nBest,\nEmre Baser 5",
  },
  {
    student_name: "Emre Baser 6",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Withdrawal Form Help",
    body: "Hi Academic Advising Team,\n\nWhere can I find the course withdrawal paperwork and who needs to sign it?\n\nBest,\nEmre Baser 6",
  },
  {
    student_name: "Emre Baser 7",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Advising Appointment",
    body: "Hi Academic Advising Team,\n\nHow can I schedule an advising appointment?\n\nBest,\nEmre Baser 7",
  },
  {
    student_name: "Emre Baser 8",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Virtual Meeting",
    body: "Hi Academic Advising Team,\n\nCan I book a Zoom advising meeting if I am off campus?\n\nBest,\nEmre Baser 8",
  },
  {
    student_name: "Emre Baser 9",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Navigate App Question",
    body: "Hi Academic Advising Team,\n\nHow do I find a time to talk to my advisor in the Navigate app?\n\nBest,\nEmre Baser 9",
  },
  {
    student_name: "Emre Baser 10",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Switching Majors",
    body: "Hi Academic Advising Team,\n\nI want to switch majors. How can I change my major?\n\nBest,\nEmre Baser 10",
  },
  {
    student_name: "Emre Baser 11",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Major Change Form",
    body: "Hi Academic Advising Team,\n\nWhere do I submit the major change form for IEOR?\n\nBest,\nEmre Baser 11",
  },
  {
    student_name: "Emre Baser 12",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Ready To Switch?",
    body: "Hi Academic Advising Team,\n\nHave I fulfilled enough requirements to switch majors?\n\nBest,\nEmre Baser 12",
  },
  {
    student_name: "Emre Baser 13",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Declare Minor",
    body: "Hi Academic Advising Team,\n\nHow can I declare a minor?\n\nBest,\nEmre Baser 13",
  },
  {
    student_name: "Emre Baser 14",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Minor Form Location",
    body: "Hi Academic Advising Team,\n\nWhere can I find the form to add or drop a minor?\n\nBest,\nEmre Baser 14",
  },
  {
    student_name: "Emre Baser 15",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Minor Completion",
    body: "Hi Academic Advising Team,\n\nI finished the requirements for my minor. What should I do next?\n\nBest,\nEmre Baser 15",
  },
  {
    student_name: "Emre Baser 16",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Major Requirements Info",
    body: "Hi Academic Advising Team,\n\nWhere can I find the requirements for my IEOR major?\n\nBest,\nEmre Baser 16",
  },
  {
    student_name: "Emre Baser 17",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "IEOR Core Question",
    body: "Hi Academic Advising Team,\n\nDoes this class count toward the IEOR core requirements?\n\nBest,\nEmre Baser 17",
  },
  {
    student_name: "Emre Baser 18",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Double Counting Major",
    body: "Hi Academic Advising Team,\n\nCan I double count a class for the IEOR major?\n\nBest,\nEmre Baser 18",
  },
  {
    student_name: "Emre Baser 19",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Minor Requirements Info",
    body: "Hi Academic Advising Team,\n\nWhat are the requirements for my minor?\n\nBest,\nEmre Baser 19",
  },
  {
    student_name: "Emre Baser 20",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Minor Double Count",
    body: "Hi Academic Advising Team,\n\nCan I double count this class for my minor too?\n\nBest,\nEmre Baser 20",
  },
  {
    student_name: "Emre Baser 21",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Old Requirements",
    body: "Hi Academic Advising Team,\n\nMy major requirements changed. Can I use the old ones instead?\n\nBest,\nEmre Baser 21",
  },
  {
    student_name: "Emre Baser 22",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Catalog Year Question",
    body: "Hi Academic Advising Team,\n\nDo I follow the catalog year I started?\n\nBest,\nEmre Baser 22",
  },
  {
    student_name: "Emre Baser 23",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "CS Core Substitution",
    body: "Hi Academic Advising Team,\n\nCan I take Java, Data Structures, and Databases instead of the IEOR CS core?\n\nBest,\nEmre Baser 23",
  },
  {
    student_name: "Emre Baser 24",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "COMS Substitution",
    body: "Hi Academic Advising Team,\n\nCan I use COMS W3134 and W4111 instead of IEOR E2000?\n\nBest,\nEmre Baser 24",
  },
  {
    student_name: "Emre Baser 25",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Technical Elective",
    body: "Hi Academic Advising Team,\n\nDoes this class count toward my technical elective requirement?\n\nBest,\nEmre Baser 25",
  },
  {
    student_name: "Emre Baser 26",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Management Electives",
    body: "Hi Academic Advising Team,\n\nHow many management electives do I need to take?\n\nBest,\nEmre Baser 26",
  },
  {
    student_name: "Emre Baser 27",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Elective List",
    body: "Hi Academic Advising Team,\n\nWhere can I find a list of approved elective classes?\n\nBest,\nEmre Baser 27",
  },
  {
    student_name: "Emre Baser 28",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Petition Question",
    body: "Hi Academic Advising Team,\n\nCan I petition for this class to count as a technical elective?\n\nBest,\nEmre Baser 28",
  },
  {
    student_name: "Emre Baser 29",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Course Approval Form",
    body: "Hi Academic Advising Team,\n\nHow do I submit the IEOR course approval request form?\n\nBest,\nEmre Baser 29",
  },
  {
    student_name: "Emre Baser 30",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Double Counting Question",
    body: "Hi Academic Advising Team,\n\nCan I double count this class toward my major and my minor?\n\nBest,\nEmre Baser 30",
  },
  {
    student_name: "Emre Baser 31",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Graduation Application",
    body: "Hi Academic Advising Team,\n\nHow do I apply for graduation?\n\nBest,\nEmre Baser 31",
  },
  {
    student_name: "Emre Baser 32",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Graduation Deadline",
    body: "Hi Academic Advising Team,\n\nWhen is the graduation application deadline for Spring?\n\nBest,\nEmre Baser 32",
  },
  {
    student_name: "Emre Baser 33",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Degree Application Form",
    body: "Hi Academic Advising Team,\n\nWhere do I submit my degree application form?\n\nBest,\nEmre Baser 33",
  },
  {
    student_name: "Emre Baser 34",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "MS Express Info",
    body: "Hi Academic Advising Team,\n\nWhere can I find information about MS Express?\n\nBest,\nEmre Baser 34",
  },
  {
    student_name: "Emre Baser 35",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "MS Express Application",
    body: "Hi Academic Advising Team,\n\nHow can I apply for MS Express and do I need GRE scores?\n\nBest,\nEmre Baser 35",
  },
  {
    student_name: "Emre Baser 36",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Advanced Track Info",
    body: "Hi Academic Advising Team,\n\nWhere can I find information about the IEOR advanced track?\n\nBest,\nEmre Baser 36",
  },
  {
    student_name: "Emre Baser 37",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Advanced Track Decision",
    body: "Hi Academic Advising Team,\n\nWhat is the difference between the regular IEOR core and the advanced track?\n\nBest,\nEmre Baser 37",
  },
  {
    student_name: "Emre Baser 38",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Major Declaration Timing",
    body: "Hi Academic Advising Team,\n\nWhen will I declare my major?\n\nBest,\nEmre Baser 38",
  },
  {
    student_name: "Emre Baser 39",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Choosing IEOR Major",
    body: "Hi Academic Advising Team,\n\nHow do I choose which IEOR major to declare?\n\nBest,\nEmre Baser 39",
  },
  {
    student_name: "Emre Baser 40",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Research Opportunities",
    body: "Hi Academic Advising Team,\n\nI want to get involved in IEOR research. Where should I look?\n\nBest,\nEmre Baser 40",
  },
  {
    student_name: "Emre Baser 41",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Research For Credit",
    body: "Hi Academic Advising Team,\n\nHow can I complete research for credit?\n\nBest,\nEmre Baser 41",
  },
  {
    student_name: "Emre Baser 42",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Study Abroad Eligibility",
    body: "Hi Academic Advising Team,\n\nAm I able to study abroad and still meet my requirements?\n\nBest,\nEmre Baser 42",
  },
  {
    student_name: "Emre Baser 43",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Classes Abroad",
    body: "Hi Academic Advising Team,\n\nWhich classes can I take abroad for IEOR credit?\n\nBest,\nEmre Baser 43",
  },
  {
    student_name: "Emre Baser 44",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Struggling In Classes",
    body: "Hi Academic Advising Team,\n\nI am struggling in my classes this semester. Who can help?\n\nBest,\nEmre Baser 44",
  },
  {
    student_name: "Emre Baser 45",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Support Resources",
    body: "Hi Academic Advising Team,\n\nI need academic support resources because of stress. Any suggestions?\n\nBest,\nEmre Baser 45",
  },
  {
    student_name: "Emre Baser 46",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Barnard 4+1 Requirements",
    body: "Hi Academic Advising Team,\n\nWhat are the requirements for the Barnard 4+1 pathway in IEOR?\n\nBest,\nEmre Baser 46",
  },
  {
    student_name: "Emre Baser 47",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Barnard 4+1 Deadline",
    body: "Hi Academic Advising Team,\n\nWhen is the Barnard 4+1 application due?\n\nBest,\nEmre Baser 47",
  },
  {
    student_name: "Emre Baser 48",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "3+2 Program Info",
    body: "Hi Academic Advising Team,\n\nHow does the Columbia 3+2 program work?\n\nBest,\nEmre Baser 48",
  },
  {
    student_name: "Emre Baser 49",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "3+2 Requirements",
    body: "Hi Academic Advising Team,\n\nWhat are the requirements for the 3+2 program?\n\nBest,\nEmre Baser 49",
  },
  {
    student_name: "Emre Baser 50",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Elective Planning",
    body: "Hi Academic Advising Team,\n\nCan we meet to review which electives align best with my goals?\n\nBest,\nEmre Baser 50",
  },
];