// Frontend/code/components/sample-emails.ts

export type SampleEmail = {
  student_name: string;
  uni: string;
  email: string;
  subject: string;
  body: string;
};

export const SAMPLE_EMAILS: SampleEmail[] = [
  {
    student_name: "Emre Baser 1",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Registration Deadline Question",
    body: "Hi Academic Advising Team,\n\nWhen is the deadline to register for classes?\n\nBest,\nEmre Baser 1",
  },
  {
    student_name: "Emre Baser 2",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Add Course Timing",
    body: "Hi Academic Advising Team,\n\nHow late can I add a course this term?\n\nBest,\nEmre Baser 2",
  },
  {
    student_name: "Emre Baser 3",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Registration Window",
    body: "Hi Academic Advising Team,\n\nWhen does the registration window close for fall?\n\nBest,\nEmre Baser 3",
  },
  {
    student_name: "Emre Baser 4",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Course Withdrawal Question",
    body: "Hi Academic Advising Team,\n\nHow do I drop a class after the deadline?\n\nBest,\nEmre Baser 4",
  },
  {
    student_name: "Emre Baser 5",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Need To Withdraw",
    body: "Hi Academic Advising Team,\n\nI might need to withdraw from a course because of family issues. What is the process?\n\nBest,\nEmre Baser 5",
  },
  {
    student_name: "Emre Baser 6",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Withdrawal Form Help",
    body: "Hi Academic Advising Team,\n\nWhere can I find the course withdrawal paperwork and who needs to sign it?\n\nBest,\nEmre Baser 6",
  },
  {
    student_name: "Emre Baser 7",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Advising Appointment",
    body: "Hi Academic Advising Team,\n\nHow can I schedule an advising appointment?\n\nBest,\nEmre Baser 7",
  },
  {
    student_name: "Emre Baser 8",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Virtual Meeting",
    body: "Hi Academic Advising Team,\n\nCan I book a Zoom advising meeting if I am off campus?\n\nBest,\nEmre Baser 8",
  },
  {
    student_name: "Emre Baser 9",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Navigate App Question",
    body: "Hi Academic Advising Team,\n\nHow do I find a time to talk to my advisor in the Navigate app?\n\nBest,\nEmre Baser 9",
  },
  {
    student_name: "Emre Baser 10",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Switching Majors",
    body: "Hi Academic Advising Team,\n\nI want to switch majors. How can I change my major?\n\nBest,\nEmre Baser 10",
  },
  {
    student_name: "Emre Baser 11",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Major Change Form",
    body: "Hi Academic Advising Team,\n\nWhere do I submit the major change form for IEOR?\n\nBest,\nEmre Baser 11",
  },
  {
    student_name: "Emre Baser 12",
    uni: "eb3514",
    email: "eb3514@columbia.edu",
    subject: "Ready To Switch?",
    body: "Hi Academic Advising Team,\n\nHave I fulfilled enough requirements to switch majors?\n\nBest,\nEmre Baser 12",
  },
  {
    student_name: "Lara Jones 13",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "Declare Minor",
    body: "Hi Academic Advising Team,\n\nHow can I declare a minor?\n\nBest,\nLara Jones 13",
  },
  {
    student_name: "Lara Jones 14",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "Minor Form Location",
    body: "Hi Academic Advising Team,\n\nWhere can I find the form to add or drop a minor?\n\nBest,\nLara Jones 14",
  },
  {
    student_name: "Lara Jones 15",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "Minor Completion",
    body: "Hi Academic Advising Team,\n\nI finished the requirements for my minor. What should I do next?\n\nBest,\nLara Jones 15",
  },
  {
    student_name: "Lara Jones 16",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "Major Requirements Info",
    body: "Hi Academic Advising Team,\n\nWhere can I find the requirements for my IEOR major?\n\nBest,\nLara Jones 16",
  },
  {
    student_name: "Lara Jones 17",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "IEOR Core Question",
    body: "Hi Academic Advising Team,\n\nDoes this class count toward the IEOR core requirements?\n\nBest,\nLara Jones 17",
  },
  {
    student_name: "Lara Jones 18",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "Double Counting Major",
    body: "Hi Academic Advising Team,\n\nCan I double count a class for the IEOR major?\n\nBest,\nLara Jones 18",
  },
  {
    student_name: "Lara Jones 19",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "Minor Requirements Info",
    body: "Hi Academic Advising Team,\n\nWhat are the requirements for my minor?\n\nBest,\nLara Jones 19",
  },
  {
    student_name: "Lara Jones 20",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "Minor Double Count",
    body: "Hi Academic Advising Team,\n\nCan I double count this class for my minor too?\n\nBest,\nLara Jones 20",
  },
  {
    student_name: "Lara Jones 21",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "Old Requirements",
    body: "Hi Academic Advising Team,\n\nMy major requirements changed. Can I use the old ones instead?\n\nBest,\nLara Jones 21",
  },
  {
    student_name: "Lara Jones 22",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "Catalog Year Question",
    body: "Hi Academic Advising Team,\n\nDo I follow the catalog year I started?\n\nBest,\nLara Jones 22",
  },
  {
    student_name: "Lara Jones 23",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "CS Core Substitution",
    body: "Hi Academic Advising Team,\n\nCan I take Java, Data Structures, and Databases instead of the IEOR CS core?\n\nBest,\nLara Jones 23",
  },
  {
    student_name: "Lara Jones 24",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "COMS Substitution",
    body: "Hi Academic Advising Team,\n\nCan I use COMS W3134 and W4111 instead of IEOR E2000?\n\nBest,\nLara Jones 24",
  },
  {
    student_name: "Lara Jones 25",
    uni: "lj2574",
    email: "lj2574@columbia.edu",
    subject: "Technical Elective",
    body: "Hi Academic Advising Team,\n\nDoes this class count toward my technical elective requirement?\n\nBest,\nLara Jones 25",
  },
  {
    student_name: "Mayyada Shair 26",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "Management Electives",
    body: "Hi Academic Advising Team,\n\nHow many management electives do I need to take?\n\nBest,\nMayyada Shair 26",
  },
  {
    student_name: "Mayyada Shair 27",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "Elective List",
    body: "Hi Academic Advising Team,\n\nWhere can I find a list of approved elective classes?\n\nBest,\nMayyada Shair 27",
  },
  {
    student_name: "Mayyada Shair 28",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "Petition Question",
    body: "Hi Academic Advising Team,\n\nCan I petition for this class to count as a technical elective?\n\nBest,\nMayyada Shair 28",
  },
  {
    student_name: "Mayyada Shair 29",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "Course Approval Form",
    body: "Hi Academic Advising Team,\n\nHow do I submit the IEOR course approval request form?\n\nBest,\nMayyada Shair 29",
  },
  {
    student_name: "Mayyada Shair 30",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "Double Counting Question",
    body: "Hi Academic Advising Team,\n\nCan I double count this class toward my major and my minor?\n\nBest,\nMayyada Shair 30",
  },
  {
    student_name: "Mayyada Shair 31",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "Graduation Application",
    body: "Hi Academic Advising Team,\n\nHow do I apply for graduation?\n\nBest,\nMayyada Shair 31",
  },
  {
    student_name: "Mayyada Shair 32",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "Graduation Deadline",
    body: "Hi Academic Advising Team,\n\nWhen is the graduation application deadline for Spring?\n\nBest,\nMayyada Shair 32",
  },
  {
    student_name: "Mayyada Shair 33",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "Degree Application Form",
    body: "Hi Academic Advising Team,\n\nWhere do I submit my degree application form?\n\nBest,\nMayyada Shair 33",
  },
  {
    student_name: "Mayyada Shair 34",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "MS Express Info",
    body: "Hi Academic Advising Team,\n\nWhere can I find information about MS Express?\n\nBest,\nMayyada Shair 34",
  },
  {
    student_name: "Mayyada Shair 35",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "MS Express Application",
    body: "Hi Academic Advising Team,\n\nHow can I apply for MS Express and do I need GRE scores?\n\nBest,\nMayyada Shair 35",
  },
  {
    student_name: "Mayyada Shair 36",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "Advanced Track Info",
    body: "Hi Academic Advising Team,\n\nWhere can I find information about the IEOR advanced track?\n\nBest,\nMayyada Shair 36",
  },
  {
    student_name: "Mayyada Shair 37",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "Advanced Track Decision",
    body: "Hi Academic Advising Team,\n\nWhat is the difference between the regular IEOR core and the advanced track?\n\nBest,\nMayyada Shair 37",
  },
  {
    student_name: "Mayyada Shair 38",
    uni: "mos2125",
    email: "mos2125@columbia.edu",
    subject: "Major Declaration Timing",
    body: "Hi Academic Advising Team,\n\nWhen will I declare my major?\n\nBest,\nMayyada Shair 38",
  },
  {
    student_name: "Yasemin Yuksel 39",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "Choosing IEOR Major",
    body: "Hi Academic Advising Team,\n\nHow do I choose which IEOR major to declare?\n\nBest,\nYasemin Yuksel 39",
  },
  {
    student_name: "Yasemin Yuksel 40",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "Research Opportunities",
    body: "Hi Academic Advising Team,\n\nI want to get involved in IEOR research. Where should I look?\n\nBest,\nYasemin Yuksel 40",
  },
  {
    student_name: "Yasemin Yuksel 41",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "Research For Credit",
    body: "Hi Academic Advising Team,\n\nHow can I complete research for credit?\n\nBest,\nYasemin Yuksel 41",
  },
  {
    student_name: "Yasemin Yuksel 42",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "Study Abroad Eligibility",
    body: "Hi Academic Advising Team,\n\nAm I able to study abroad and still meet my requirements?\n\nBest,\nYasemin Yuksel 42",
  },
  {
    student_name: "Yasemin Yuksel 43",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "Classes Abroad",
    body: "Hi Academic Advising Team,\n\nWhich classes can I take abroad for IEOR credit?\n\nBest,\nYasemin Yuksel 43",
  },
  {
    student_name: "Yasemin Yuksel 44",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "Struggling In Classes",
    body: "Hi Academic Advising Team,\n\nI am struggling in my classes this semester. Who can help?\n\nBest,\nYasemin Yuksel 44",
  },
  {
    student_name: "Yasemin Yuksel 45",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "Support Resources",
    body: "Hi Academic Advising Team,\n\nI need academic support resources because of stress. Any suggestions?\n\nBest,\nYasemin Yuksel 45",
  },
  {
    student_name: "Yasemin Yuksel 46",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "Barnard 4+1 Requirements",
    body: "Hi Academic Advising Team,\n\nWhat are the requirements for the Barnard 4+1 pathway in IEOR?\n\nBest,\nYasemin Yuksel 46",
  },
  {
    student_name: "Yasemin Yuksel 47",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "Barnard 4+1 Deadline",
    body: "Hi Academic Advising Team,\n\nWhen is the Barnard 4+1 application due?\n\nBest,\nYasemin Yuksel 47",
  },
  {
    student_name: "Yasemin Yuksel 48",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "3+2 Program Info",
    body: "Hi Academic Advising Team,\n\nHow does the Columbia 3+2 program work?\n\nBest,\nYasemin Yuksel 48",
  },
  {
    student_name: "Yasemin Yuksel 49",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "3+2 Requirements",
    body: "Hi Academic Advising Team,\n\nWhat are the requirements for the 3+2 program?\n\nBest,\nYasemin Yuksel 49",
  },
  {
    student_name: "Yasemin Yuksel 50",
    uni: "yy3294",
    email: "yy3294@columbia.edu",
    subject: "Elective Planning",
    body: "Hi Academic Advising Team,\n\nCan we meet to review which electives align best with my goals?\n\nBest,\nYasemin Yuksel 50",
  },
];
